SELECT EMP_NAME FROM EMPLOYEE;
-- asterisk (*) : 모든 테이블
-EMPLOYEE

SELECT *;
FROM EMPLOYEE;

-- DEPARTMENT 테이블의 부서코드, 부서명 조회
SELECT DEPT_ID, DEPT_TITLE
FROM DEPARTMENT;

-- DEPARTMENT 테이블의 모든 데이터 조회
SELECT * FROM DEPARTMENT;

